In [3]:
import uproot
import pandas

In [2]:
flat_tree = uproot.open('344180ade_cgeeMaker.root')['Nominal']

In [4]:
print(flat_tree.keys())

['nJets', 'matchB1', 'matchB2', 'passg10', 'passg15', 'passg20', 'passg25', 'passg35', 'passg40', 'passg45', 'passg50', 'passg60', 'passg70', 'passg80', 'passTrig', 'passg100', 'passg120', 'passVBF0b', 'passVBF18', 'passVBF1b', 'passVBF20', 'passVBF22', 'passVBF2b', 'matchVBF0b', 'passEM13VH', 'passEM15VH', 'passEM18VH', 'passEM20VH', 'passVBF1bs', 'passVBF2bs', 'tagCatExcl', 'passEM22VHI', 'passVBF25g4j', 'passMVAPreSel', 'MCChannelNumber', 'randomRunNumber', 'passVBF1bmv2c10s', 'passVBF2bmv2c10s', 'passVBFbmv2c10s500', 'passVBFbmv2c10s500gsc', 'RunNumber', 'EventNumber', 'BDT', 'zep', 'pTB1', 'pTB2', 'pTBB', 'pTJ1', 'pTJ2', 'pTJ4', 'pTPh', 'zeta', 'etaJ1', 'etaJ2', 'etaJ5', 'pTBal', 'phEta', 'JJasym', 'dEtabb', 'dPhibb', 'dRB1J1', 'dRB1Ph', 'dRB2Ph', 'cenPhJJ', 'hlt_mjj', 'l1_emet', 'pTJ1cen', 'MV2c10B1', 'MV2c10B2', 'arctanbb', 'cosAlpha', 'dEtaBBJJ', 'dPhiBBJJ', 'etaJ1cen', 'hlt_j1pt', 'hlt_j2pt', 'hlt_j3pt', 'hlt_j4pt', 'hlt_j5pt', 'hlt_phpt', 'mindRBPh', 'cosThetaC', 'hlt_mjj_phor', 'hlt_j4pt_phor', 'hlt_phpt_matched', 'mBB', 'mJJ', 'pTJJ', 'dEtaJJ', 'pTJJSF', 'pTBalSF', 'dEtaJJSF', 'dRB1PhSF', 'dRB2PhSF', 'EventWeight', 'bjetTrigPt_SF', 'bjetTrigEta_SF']

In [16]:
df = pandas.DataFrame(flat_tree.to_numpy(), columns=flat_tree.keys())

AttributeError: 'Model_TTree_v20' object has no attribute 'to_numpy'

In [15]:
df

,nJets,matchB1,matchB2,passg10,passg15,passg20,passg25,passg35,passg40,passg45,...,pTJJ,dEtaJJ,pTJJSF,pTBalSF,dEtaJJSF,dRB1PhSF,dRB2PhSF,EventWeight,bjetTrigPt_SF,bjetTrigEta_SF
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
92,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
93,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
94,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
95,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
96,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [17]:
df2 = flat_tree.arrays(flat_tree.keys(), library="pd")

In [18]:
df2

,nJets,matchB1,matchB2,passg10,passg15,passg20,passg25,passg35,passg40,passg45,...,pTJJ,dEtaJJ,pTJJSF,pTBalSF,dEtaJJSF,dRB1PhSF,dRB2PhSF,EventWeight,bjetTrigPt_SF,bjetTrigEta_SF
0,4,0,0,1,1,1,0,0,0,0,...,34520.033091,0.828766,1.141439,0.955773,3.620309,1.031644,0.637922,0.374269,1.960889,0.957245
1,4,0,1,1,1,1,1,1,1,1,...,98954.491496,4.262229,1.051258,1.003408,0.962143,1.002355,0.941527,0.002176,1.313052,0.944131
2,4,0,0,1,1,1,1,1,1,1,...,94667.776574,6.678960,1.056484,0.968873,0.902313,1.115714,1.005775,0.004219,1.788464,0.974127
3,4,1,1,1,1,1,1,1,1,1,...,206225.146558,0.649043,0.956381,1.001207,3.734147,0.937815,1.071024,0.357881,0.968463,0.973856
4,6,1,1,1,1,1,1,1,1,1,...,65142.802138,3.250207,1.095474,0.971238,1.237956,0.808340,1.042439,0.342875,0.967115,0.969389
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2542826,6,0,0,1,1,1,1,1,1,0,...,53980.095260,1.959420,1.111577,1.065097,2.364383,1.004822,1.133425,0.483134,1.790635,0.951513
2542827,6,0,0,1,1,1,1,1,1,1,...,87624.856049,3.515982,1.065310,0.950768,1.126363,1.122281,1.090077,0.005803,1.822549,0.968467
2542828,4,0,0,1,1,1,1,1,1,1,...,90270.571894,0.868855,1.061959,1.001151,3.589757,1.133232,1.133138,0.483198,1.911454,0.947736
2542829,5,0,0,1,1,1,1,0,0,0,...,67579.636880,4.631943,1.092058,1.149139,0.930389,0.868251,0.979311,0.004440,1.699131,0.972344
2542830,4,0,0,1,1,1,1,1,0,0,...,28618.013503,0.478187,1.150945,0.968975,3.804017,0.831615,1.041979,0.000052,1.778738,0.970980

In [19]:
df2.to_hdf('test.hdf',key='df')

## Test reading the HDF file back into Python

In [20]:
import h5py

In [23]:
input_file = h5py.File('test.hdf','r')